BEGIN;

TRUNCATE TABLE reading_logs RESTART IDENTITY CASCADE;

TRUNCATE TABLE notes RESTART IDENTITY CASCADE;

TRUNCATE TABLE books RESTART IDENTITY CASCADE;

TRUNCATE TABLE users RESTART IDENTITY CASCADE;

COMMIT;